# Generated by Django 5.1.2 on 2024-11-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_is_athlete_user_is_coach_user_is_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='competition',
            name='event_type',
            field=models.CharField(choices=[('competição', 'Competição'), ('treinamento', 'Treinamento'), ('outro', 'Outro')], default='competição', max_length=20),
        ),
    ]
