# Generated by Django 5.1.2 on 2024-11-25 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_competition_description_competition_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor', to='app.user'),
        ),
    ]
