# Generated by Django 5.1.2 on 2024-11-27 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sponsor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='modalities',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='user',
        ),
        migrations.AlterField(
            model_name='athlete',
            name='competition_history',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='functional_classification',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='personal_records',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='photos',
        ),
        migrations.AlterField(
            model_name='athlete',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='athlete_photos/'),
        ),
    ]
