# Generated by Django 5.1.2 on 2024-11-27 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_athletelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='modalities',
        ),
    ]
